### ISSUE TITLE
DEVNET_PRIVKEY = "WHERE DO I GET THIS KEY?"

### ISSUE THREAD

**Issue by journey-ETH** [OffchainLabs/arbitrum-tutorials#32]
Good morning to all these doing some tests for testnet and continue to mainnet full node.

I have this doubt.

How do I get the key: DEVNET_PRIVKEY = "0x KEY?"
Please help me greetings

**Comment by ControlCplusControlV** [comment]
This is an Ethereum private key that has access to your testnet funds

https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key

Is how to do it on metamask. it should be clear this should only have testnet funds (ie don't use the same wallet for testnet and mainnet) 

I recommend closing this issue and instead waiting for courses as this is considered common knowledge, and issues are meant to document errors, rather than as a help section.

**Comment by EricaNichol** [comment]
the documentation is not that great

**Comment by ControlCplusControlV** [comment]
I agree their docs aren't the greatest, but not knowing what a private key is isn't an Arbitrum specific issue. Its one of the most basic things next to what a wallet is. Plenty of other resources like Hardhat will teach you what they are and how to use them, and if you are using a layer 2 SDK some technical knowledge is to be expected

**Comment by zbcoding** [comment]
I kept getting a url error. Have to put the private key inside quotes, without 0x in front.
Delete the comment in the env file too.
e.g.
DEVNET_PRIVKEY="ccccddddd12accc95cccccc85f0c7ccccc63ccc4dc5dccccc7c1dddd566ccccc"
L2RPC="https://rinkeby.arbitrum.io/rpc"
